apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao
spec:
  selector:
    matchLabels:
      app: api-conversao
  template:
    metadata:
      labels:
        app: api-conversao
    spec:
      containers:
      - name: api-conversao
        image: eduardoney/api-conversao:1.0
        ports:
        - containerPort: 8080
